Algoritmo "ex3"

Var
num1 : Real
num2 : Real


Inicio
Escreval("Digite dois numeros distintos")
Escreval("------------------------------")
Escreval("Digite o primeiro numero: ")
leia(num1)
Escreval("------------------------------")
Escreval("Digite o segundo numero: ")
leia(num2)

se(num1 > num2) entao
Escreval("------------------------------")
Escreval(num1, " é o maior numero")
senao
Escreval("------------------------------")
Escreval(num2, " é o maior numero")
Fimse
